#ifndef MESSAGE_H_
#define MESSAGE_H_

#define MESSAGE_SIZE 100

typedef enum MessageType {
	MESSAGE_TYPE_REGISTER_AS = 0,
	MESSAGE_TYPE_WHOIS,
	MESSAGE_TYPE_WHOIS_REPLY,
	MESSAGE_TYPE_SIGN_UP,
	MESSAGE_TYPE_CHOOSE,
	MESSAGE_TYPE_PLAY,
	MESSAGE_TYPE_RESULT,
	MESSAGE_TYPE_QUIT,
	MESSAGE_TYPE_GOODBYE,
} MessageType;

#endif /* MESSAGE_H_ */
