#ifndef PRIORITIES_H__
#define PRIORITIES_H__


#define	CLOCKSERVER_START_PRIORITY		0
#define	CLOCKNOTIFIER_START_PRIORITY		0
#define	FIRSTTASK_START_PRIORITY		0
#define	NAMESERVER_START_PRIORITY		1
#define	ADMINISTRATORTASK_START_PRIORITY	2
#define	RPSTESTSTART_PRIORITY			3
#define	UARTBOOTSTRAPTASK_START_PRIORITY	8
#define	TRAINSERVER_START_PRIORITY		8
#define KEYBOARDINPUTNOTIFIER_START_PRIORITY	8
#define SCREENOUTPUTNOTIFIER_START_PRIORITY	8
#define TRAININPUTNOTIFIER_START_PRIORITY	8
#define TRAINOUTPUTNOTIFIER_START_PRIORITY	8
#define UITIMER_START_PRIORITY			8
#define TRAINSENSORREADER_START_PRIORITY	8
#define TRAINCOMMANDSERVER_START_PRIORITY	8
#define TRAINSERVERTIMER_START_PRIORITY		8

#define	RPSSERVER_START_PRIORITY		16
#define	UISERVER_START_PRIORITY			16
#define KEYBOARDINPUTSERVER_START_PRIORITY	8
#define SCREENOUTPUTSERVER_START_PRIORITY	16
#define TRAININPUTSERVER_START_PRIORITY		16
#define TRAINOUTPUTSERVER_START_PRIORITY	16
#define TRAINIONOTIFIER_START_PRIORITY		16
#define UIKEYBOARDINPUT_START_PRIORITY		16
#define	RPSSERVER_START_PRIORITY		16
#define	RPSCLIENT_START_PRIORITY		24
#define	IDLETASK_START_PRIORITY			24

#define	CLOCKCLIENT_START_PRIORITY_3		3
#define	CLOCKCLIENT_START_PRIORITY_4		4
#define	CLOCKCLIENT_START_PRIORITY_5		5
#define	CLOCKCLIENT_START_PRIORITY_6		6




#endif
