#ifndef PRIORITIES_H__
#define PRIORITIES_H__


#define	CLOCKSERVER_START_PRIORITY		HIGHEST
#define	CLOCKNOTIFIER_START_PRIORITY		HIGHEST
#define	FIRSTTASK_START_PRIORITY		HIGHEST
#define	NAMESERVER_START_PRIORITY		(HIGHEST+1)
#define	ADMINISTRATORTASK_START_PRIORITY	(HIGHEST+2)
#define	RPSTESTSTART_PRIORITY			(HIGHEST+3)
#define	UARTBOOTSTRAPTASK_START_PRIORITY	HIGH
#define	TRAINSERVER_START_PRIORITY		HIGH
#define KEYBOARDINPUTNOTIFIER_START_PRIORITY	HIGH
#define SCREENOUTPUTNOTIFIER_START_PRIORITY	HIGH
#define TRAININPUTNOTIFIER_START_PRIORITY	HIGH
#define TRAINOUTPUTNOTIFIER_START_PRIORITY	HIGH
#define UITIMER_START_PRIORITY			HIGH
#define	RPSSERVER_START_PRIORITY		NORMAL
#define	UISERVER_START_PRIORITY			NORMAL
#define KEYBOARDINPUTSERVER_START_PRIORITY	HIGH
#define SCREENOUTPUTSERVER_START_PRIORITY	NORMAL
#define TRAININPUTSERVER_START_PRIORITY		NORMAL
#define TRAINOUTPUTSERVER_START_PRIORITY	NORMAL
#define TRAINIONOTIFIER_START_PRIORITY		NORMAL
#define UIKEYBOARDINPUT_START_PRIORITY		NORMAL
#define	RPSCLIENT_START_PRIORITY		LOW

#define	CLOCKCLIENT_START_PRIORITY_3		3
#define	CLOCKCLIENT_START_PRIORITY_4		4
#define	CLOCKCLIENT_START_PRIORITY_5		5
#define	CLOCKCLIENT_START_PRIORITY_6		6




#endif
